
package aspera.central._2012._10.transfer201210;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import aspera.xml.faspsessionnet._2006._01.types.SetBandwidthCapRequest;
import aspera.xml.faspsessionnet._2006._01.types.SetBandwidthCapResponse;
import aspera.xml.faspsessionnet._2006._01.types.SetMinimumRateRequest;
import aspera.xml.faspsessionnet._2006._01.types.SetMinimumRateResponse;
import aspera.xml.faspsessionnet._2006._01.types.SetPolicyRequest;
import aspera.xml.faspsessionnet._2006._01.types.SetPolicyResponse;
import aspera.xml.faspsessionnet._2006._01.types.SetRateParametersRequest;
import aspera.xml.faspsessionnet._2006._01.types.SetRateParametersResponse;
import aspera.xml.faspsessionnet._2006._01.types.SetTargetRateRequest;
import aspera.xml.faspsessionnet._2006._01.types.SetTargetRateResponse;
import aspera.xml.faspsessionnet._2009._11.types.GetFileTransferInfoRequest;
import aspera.xml.faspsessionnet._2009._11.types.GetFileTransferInfoResponse;
import aspera.xml.faspsessionnet._2009._11.types.GetFileTransferStatisticsRequest;
import aspera.xml.faspsessionnet._2009._11.types.GetFileTransferStatisticsResponse;
import aspera.xml.faspsessionnet._2009._11.types.GetFileTransfersRequest;
import aspera.xml.faspsessionnet._2009._11.types.GetFileTransfersResponse;
import aspera.xml.faspsessionnet._2009._11.types.GetInfoRequest;
import aspera.xml.faspsessionnet._2009._11.types.GetInfoResponse;
import aspera.xml.faspsessionnet._2009._11.types.GetSessionInfoRequest;
import aspera.xml.faspsessionnet._2009._11.types.GetSessionInfoResponse;
import aspera.xml.faspsessionnet._2009._11.types.GetSessionStatisticsRequest;
import aspera.xml.faspsessionnet._2009._11.types.GetSessionStatisticsResponse;
import aspera.xml.faspsessionnet._2009._11.types.GetSessionsRequest;
import aspera.xml.faspsessionnet._2009._11.types.GetSessionsResponse;
import aspera.xml.faspsessionnet._2009._11.types.GetStatisticsRequest;
import aspera.xml.faspsessionnet._2009._11.types.GetStatisticsResponse;
import aspera.xml.iscptransfernet._2006._04.types.ListJobsRequest;
import aspera.xml.iscptransfernet._2006._04.types.ListJobsResponse;
import aspera.xml.jobnet._2006._01.types.ListTypesRequest;
import aspera.xml.jobnet._2006._01.types.ListTypesResponse;
import aspera.xml.jobnet._2006._01.types.SubmitRequest;
import aspera.xml.jobnet._2006._01.types.SubmitResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FASPSoap", targetNamespace = "urn:Aspera:Central:2012/10:Transfer201210")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    aspera.xml.faspsessionnet._2006._01.types.ObjectFactory.class,
    aspera.xml.faspsessionnet._2009._11.types.ObjectFactory.class,
    aspera.xml.iscptransfernet._2006._04.types.ObjectFactory.class,
    aspera.xml.jobnet._2006._01.types.ObjectFactory.class
})
public interface FASPSoap {


    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.jobnet._2006._01.types.ListTypesResponse
     */
    @WebMethod(operationName = "ListTypes", action = "JobNET-200601#ListTypes")
    @WebResult(name = "ListTypesResponse", targetNamespace = "urn:Aspera:XML:JobNET:2006/01:Types", partName = "parameters")
    public ListTypesResponse listTypes(
        @WebParam(name = "ListTypesRequest", targetNamespace = "urn:Aspera:XML:JobNET:2006/01:Types", partName = "parameters")
        ListTypesRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.jobnet._2006._01.types.SubmitResponse
     * @throws JobTypeNotFoundFault
     * @throws JobFormatInvalidFault
     * @throws JobSubmissionErrorFault
     */
    @WebMethod(operationName = "Submit", action = "JobNET-200601#Submit")
    @WebResult(name = "SubmitResponse", targetNamespace = "urn:Aspera:XML:JobNET:2006/01:Types", partName = "parameters")
    public SubmitResponse submit(
        @WebParam(name = "SubmitRequest", targetNamespace = "urn:Aspera:XML:JobNET:2006/01:Types", partName = "parameters")
        SubmitRequest parameters)
        throws JobFormatInvalidFault, JobSubmissionErrorFault, JobTypeNotFoundFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.iscptransfernet._2006._04.types.ListJobsResponse
     */
    @WebMethod(operationName = "ListJobs", action = "IScpTransferNET-200604#ListJobs")
    @WebResult(name = "ListJobsResponse", targetNamespace = "urn:Aspera:XML:IScpTransferNET:2006/04:Types", partName = "parameters")
    public ListJobsResponse listJobs(
        @WebParam(name = "ListJobsRequest", targetNamespace = "urn:Aspera:XML:IScpTransferNET:2006/04:Types", partName = "parameters")
        ListJobsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.iscptransfernet._2006._04.types.CancelResponse
     * @throws JobNotFoundFault
     */
    @WebMethod(operationName = "CancelJob", action = "IScpTransferNET-200604#Cancel")
    @WebResult(name = "CancelResponse", targetNamespace = "urn:Aspera:XML:IScpTransferNET:2006/04:Types", partName = "parameters")
    public aspera.xml.iscptransfernet._2006._04.types.CancelResponse cancelJob(
        @WebParam(name = "CancelRequest", targetNamespace = "urn:Aspera:XML:IScpTransferNET:2006/04:Types", partName = "parameters")
        aspera.xml.iscptransfernet._2006._04.types.CancelRequest parameters)
        throws JobNotFoundFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.faspsessionnet._2006._01.types.SetRateParametersResponse
     * @throws SessionNotFoundFault
     */
    @WebMethod(operationName = "SetRateParameters", action = "FASPSessionNET-200601#SetRateParameters")
    @WebResult(name = "SetRateParametersResponse", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2006/01:Types", partName = "parameters")
    public SetRateParametersResponse setRateParameters(
        @WebParam(name = "SetRateParametersRequest", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2006/01:Types", partName = "parameters")
        SetRateParametersRequest parameters)
        throws SessionNotFoundFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.faspsessionnet._2006._01.types.SetPolicyResponse
     * @throws SessionNotFoundFault
     */
    @WebMethod(operationName = "SetPolicy", action = "FASPSessionNET-200601#SetPolicy")
    @WebResult(name = "SetPolicyResponse", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2006/01:Types", partName = "parameters")
    public SetPolicyResponse setPolicy(
        @WebParam(name = "SetPolicyRequest", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2006/01:Types", partName = "parameters")
        SetPolicyRequest parameters)
        throws SessionNotFoundFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.faspsessionnet._2006._01.types.SetTargetRateResponse
     * @throws SessionNotFoundFault
     */
    @WebMethod(operationName = "SetTargetRate", action = "FASPSessionNET-200601#SetTargetRate")
    @WebResult(name = "SetTargetRateResponse", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2006/01:Types", partName = "parameters")
    public SetTargetRateResponse setTargetRate(
        @WebParam(name = "SetTargetRateRequest", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2006/01:Types", partName = "parameters")
        SetTargetRateRequest parameters)
        throws SessionNotFoundFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.faspsessionnet._2006._01.types.SetMinimumRateResponse
     * @throws SessionNotFoundFault
     */
    @WebMethod(operationName = "SetMinimumRate", action = "FASPSessionNET-200601#SetMinimumRate")
    @WebResult(name = "SetMinimumRateResponse", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2006/01:Types", partName = "parameters")
    public SetMinimumRateResponse setMinimumRate(
        @WebParam(name = "SetMinimumRateRequest", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2006/01:Types", partName = "parameters")
        SetMinimumRateRequest parameters)
        throws SessionNotFoundFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.faspsessionnet._2006._01.types.SetBandwidthCapResponse
     * @throws SessionNotFoundFault
     */
    @WebMethod(operationName = "SetBandwidthCap", action = "FASPSessionNET-200601#SetBandwidthCap")
    @WebResult(name = "SetBandwidthCapResponse", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2006/01:Types", partName = "parameters")
    public SetBandwidthCapResponse setBandwidthCap(
        @WebParam(name = "SetBandwidthCapRequest", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2006/01:Types", partName = "parameters")
        SetBandwidthCapRequest parameters)
        throws SessionNotFoundFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.faspsessionnet._2006._01.types.CancelResponse
     * @throws SessionNotFoundFault
     */
    @WebMethod(operationName = "CancelSession", action = "FASPSessionNET-200601#Cancel")
    @WebResult(name = "CancelResponse", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2006/01:Types", partName = "parameters")
    public aspera.xml.faspsessionnet._2006._01.types.CancelResponse cancelSession(
        @WebParam(name = "CancelRequest", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2006/01:Types", partName = "parameters")
        aspera.xml.faspsessionnet._2006._01.types.CancelRequest parameters)
        throws SessionNotFoundFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.faspsessionnet._2009._11.types.GetSessionsResponse
     * @throws FilterChangedErrorFault
     */
    @WebMethod(operationName = "GetSessions", action = "FASPSessionNET-200911#GetSessions")
    @WebResult(name = "GetSessionsResponse", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2009/11:Types", partName = "parameters")
    public GetSessionsResponse getSessions(
        @WebParam(name = "GetSessionsRequest", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2009/11:Types", partName = "parameters")
        GetSessionsRequest parameters)
        throws FilterChangedErrorFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.faspsessionnet._2009._11.types.GetSessionInfoResponse
     * @throws FilterChangedErrorFault
     */
    @WebMethod(operationName = "GetSessionInfo", action = "FASPSessionNET-200911#GetSessionInfo")
    @WebResult(name = "GetSessionInfoResponse", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2009/11:Types", partName = "parameters")
    public GetSessionInfoResponse getSessionInfo(
        @WebParam(name = "GetSessionInfoRequest", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2009/11:Types", partName = "parameters")
        GetSessionInfoRequest parameters)
        throws FilterChangedErrorFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.faspsessionnet._2009._11.types.GetSessionStatisticsResponse
     * @throws FilterChangedErrorFault
     */
    @WebMethod(operationName = "GetSessionStatistics", action = "FASPSessionNET-200911#GetSessionStatistics")
    @WebResult(name = "GetSessionStatisticsResponse", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2009/11:Types", partName = "parameters")
    public GetSessionStatisticsResponse getSessionStatistics(
        @WebParam(name = "GetSessionStatisticsRequest", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2009/11:Types", partName = "parameters")
        GetSessionStatisticsRequest parameters)
        throws FilterChangedErrorFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.faspsessionnet._2009._11.types.GetFileTransfersResponse
     * @throws FilterChangedErrorFault
     */
    @WebMethod(operationName = "GetFileTransfers", action = "FASPSessionNET-200911#GetFileTransfers")
    @WebResult(name = "GetFileTransfersResponse", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2009/11:Types", partName = "parameters")
    public GetFileTransfersResponse getFileTransfers(
        @WebParam(name = "GetFileTransfersRequest", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2009/11:Types", partName = "parameters")
        GetFileTransfersRequest parameters)
        throws FilterChangedErrorFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.faspsessionnet._2009._11.types.GetFileTransferInfoResponse
     * @throws FilterChangedErrorFault
     */
    @WebMethod(operationName = "GetFileTransferInfo", action = "FASPSessionNET-200911#GetFileTransferInfo")
    @WebResult(name = "GetFileTransferInfoResponse", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2009/11:Types", partName = "parameters")
    public GetFileTransferInfoResponse getFileTransferInfo(
        @WebParam(name = "GetFileTransferInfoRequest", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2009/11:Types", partName = "parameters")
        GetFileTransferInfoRequest parameters)
        throws FilterChangedErrorFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.faspsessionnet._2009._11.types.GetFileTransferStatisticsResponse
     * @throws FilterChangedErrorFault
     */
    @WebMethod(operationName = "GetFileTransferStatistics", action = "FASPSessionNET-200911#GetFileTransferStatistics")
    @WebResult(name = "GetFileTransferStatisticsResponse", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2009/11:Types", partName = "parameters")
    public GetFileTransferStatisticsResponse getFileTransferStatistics(
        @WebParam(name = "GetFileTransferStatisticsRequest", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2009/11:Types", partName = "parameters")
        GetFileTransferStatisticsRequest parameters)
        throws FilterChangedErrorFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.faspsessionnet._2009._11.types.GetInfoResponse
     * @throws FilterChangedErrorFault
     */
    @WebMethod(operationName = "GetInfo", action = "FASPSessionNET-200911#GetInfo")
    @WebResult(name = "GetInfoResponse", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2009/11:Types", partName = "parameters")
    public GetInfoResponse getInfo(
        @WebParam(name = "GetInfoRequest", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2009/11:Types", partName = "parameters")
        GetInfoRequest parameters)
        throws FilterChangedErrorFault
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns aspera.xml.faspsessionnet._2009._11.types.GetStatisticsResponse
     * @throws FilterChangedErrorFault
     */
    @WebMethod(operationName = "GetStatistics", action = "FASPSessionNET-200911#GetStatistics")
    @WebResult(name = "GetStatisticsResponse", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2009/11:Types", partName = "parameters")
    public GetStatisticsResponse getStatistics(
        @WebParam(name = "GetStatisticsRequest", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2009/11:Types", partName = "parameters")
        GetStatisticsRequest parameters)
        throws FilterChangedErrorFault
    ;

}
