
package aspera.central._2012._10.transfer201210;

import javax.xml.ws.WebFault;
import aspera.xml.faspsessionnet._2009._11.types.FilterChangedErrorFaultElement;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "FilterChangedErrorFaultElement", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2009/11:Types")
public class FilterChangedErrorFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FilterChangedErrorFaultElement faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FilterChangedErrorFault(String message, FilterChangedErrorFaultElement faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FilterChangedErrorFault(String message, FilterChangedErrorFaultElement faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: aspera.xml.faspsessionnet._2009._11.types.FilterChangedErrorFaultElement
     */
    public FilterChangedErrorFaultElement getFaultInfo() {
        return faultInfo;
    }

}
