
package aspera.central._2012._10.transfer201210;

import javax.xml.ws.WebFault;
import aspera.xml.iscptransfernet._2006._04.types.JobNotFoundFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "JobNotFoundFaultType", targetNamespace = "urn:Aspera:XML:IScpTransferNET:2006/04:Types")
public class JobNotFoundFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private JobNotFoundFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public JobNotFoundFault(String message, JobNotFoundFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public JobNotFoundFault(String message, JobNotFoundFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: aspera.xml.iscptransfernet._2006._04.types.JobNotFoundFaultType
     */
    public JobNotFoundFaultType getFaultInfo() {
        return faultInfo;
    }

}
