
package aspera.central._2012._10.transfer201210;

import javax.xml.ws.WebFault;
import aspera.xml.faspsessionnet._2006._01.types.SessionNotFoundFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SessionNotFoundFaultType", targetNamespace = "urn:Aspera:XML:FASPSessionNET:2006/01:Types")
public class SessionNotFoundFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SessionNotFoundFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SessionNotFoundFault(String message, SessionNotFoundFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SessionNotFoundFault(String message, SessionNotFoundFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: aspera.xml.faspsessionnet._2006._01.types.SessionNotFoundFaultType
     */
    public SessionNotFoundFaultType getFaultInfo() {
        return faultInfo;
    }

}
