
package aspera.central._2012._10.transfer201210;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Transfer201210", targetNamespace = "urn:Aspera:Central:2012/10:Transfer201210", wsdlLocation = "http://10.10.0.62:40001/console/services/soap/Transfer201210.wsdl")
public class Transfer201210
    extends Service
{

    private final static URL TRANSFER201210_WSDL_LOCATION;
    private final static WebServiceException TRANSFER201210_EXCEPTION;
    private final static QName TRANSFER201210_QNAME = new QName("urn:Aspera:Central:2012/10:Transfer201210", "Transfer201210");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.10.0.62:40001/console/services/soap/Transfer201210.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSFER201210_WSDL_LOCATION = url;
        TRANSFER201210_EXCEPTION = e;
    }

    public Transfer201210() {
        super(__getWsdlLocation(), TRANSFER201210_QNAME);
    }

    public Transfer201210(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSFER201210_QNAME, features);
    }

    public Transfer201210(URL wsdlLocation) {
        super(wsdlLocation, TRANSFER201210_QNAME);
    }

    public Transfer201210(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSFER201210_QNAME, features);
    }

    public Transfer201210(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Transfer201210(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FASPSoap
     */
    @WebEndpoint(name = "Transfer201210Port")
    public FASPSoap getTransfer201210Port() {
        return super.getPort(new QName("urn:Aspera:Central:2012/10:Transfer201210", "Transfer201210Port"), FASPSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FASPSoap
     */
    @WebEndpoint(name = "Transfer201210Port")
    public FASPSoap getTransfer201210Port(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Aspera:Central:2012/10:Transfer201210", "Transfer201210Port"), FASPSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSFER201210_EXCEPTION!= null) {
            throw TRANSFER201210_EXCEPTION;
        }
        return TRANSFER201210_WSDL_LOCATION;
    }

}
